[profile.default]
# project
src = 'src'
test = 'test'
libs = ['node_modules']

# Optimizer
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas Report
gas_reports = ['*']
gas_reports_ignore = []
