# See more config options https://github.com/gakonst/foundry/tree/master/config
[profile.default]
# project
src = 'src'
test = 'test'
out = 'dist'
libs = ['lib']
libraries = []

# Optimizer
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas Report
gas_reports = ['*']
gas_reports_ignore = []

# rpc endpoint supported with
# Fork: `vm.createSelectFork(vm.rpcUrl("rinkeby"))`
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
kovan = "https://eth-kovan.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
ropsten = "https://eth-ropsten.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
rinkeby = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
