# See more config options https://github.com/gakonst/foundry/tree/master/config
[profile.default]
# project
src = 'src'
test = 'test'
out = 'dist'
libs = ['lib']
libraries = []

# Optimizer
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas Report
gas_reports = ['*']
gas_reports_ignore = []
